<?= $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this
                ->headTitle('ZF2 '. $this->translate('__label_app_name'))
                ->setSeparator(' - ')->setAutoEscape(false)
            ;
        ?>

        <?= $this
                ->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ;
        ?>

        <!-- Le styles -->
        <?= $this
                ->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ;
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
                ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', ['conditional' => 'lt IE 9',])
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
            ;
        ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?= $this->url('home'); ?>"><?= $this->translate('__label_app_name'); ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?= $this->url('home'); ?>"><?= $this->translate('__label_home'); ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?= $this->content; ?>
            <hr>
            <footer>
                <p><?= sprintf($this->translate('__message_colophon'), date('Y')); ?></p>
            </footer>
        </div> <!-- /container -->
        <?= $this->inlineScript(); ?>
    </body>
</html>
