<div class="hero-unit">
    <h1><?= sprintf($this->translate('__title_welcome_zf2'), '<span class="zf-green">', '</span>'); ?></h1>
    <p><?= sprintf($this->translate('__message_welcome_zf2'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION); ?></p>
    <p><a class="btn btn-success btn-large" href="https://github.com/zendframework/zf2" target="_blank"><?= $this->translate('__label_fork_on_github'); ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="span4">
        <h2><?= $this->translate('__title_follow_development'); ?></h2>
        <p><?= sprintf($this->translate('__message_follow_development'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>'); ?></p>
        <p><a class="btn btn-success" href="http://framework.zend.com/zf2" target="_blank"><?= $this->translate('__label_zf2_portal'); ?> &raquo;</a></p>
    </div>

    <div class="span4">
        <h2><?= $this->translate('__title_discover_modules'); ?></h2>
        <p><?= sprintf($this->translate('__message_discover_modules'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>'); ?></p>
        <p><a class="btn btn-success" href="http://modules.zendframework.com/" target="_blank"><?= $this->translate('__label_explore_modules'); ?> &raquo;</a></p>
   </div>

   <div class="span4">
       <h2><?= $this->translate('__title_get_support'); ?></h2>
       <p><?= sprintf($this->translate('__message_get_support'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>'); ?></p>
       <p><a class="btn btn-success" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?= $this->translate('__label_ping_on_irc'); ?> &raquo;</a></p>
   </div>
</div>